services:
  migrations:
    build:
      context: .
      dockerfile: Dockerfile.migrate
    networks:
      - local_network
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
  
  indexer:
    build:
      dockerfile: Dockerfile.indexer
      context: .
    ports:
      - "3000:3000"
    networks:
      - local_network
    environment:
      - DB_CONNECTION_STRING=postgres://postgres:postgres@db:5432/postgres
      - NODE_CONNECTION_STRING=${NODE_CONNECTION_STRING:-https://sepolia.infura.io/v3/your-api-key}
      - ROUTER_ENDPOINT=0.0.0.0:3000
      - INDEX_TRANSACTIONS=false
      - RUST_LOG=debug
      - START_BLOCK_OFFSET=100
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - local_network
    volumes:
      - db_local_data:/var/lib/postgresql/local_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  local_network:
volumes:
  db_local_data:
